# Generated by Django 6.0.4 on 2026-04-14 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='complete_by_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_period',
            field=models.CharField(choices=[('day', 'Day'), ('weekly', 'Week'), ('monthly', 'Month'), ('long', 'Long Term')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('academic', 'Academic'), ('career', 'Career'), ('life', 'Life')], max_length=10),
        ),
    ]
