# Generated by Django 6.0.4 on 2026-04-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_complete_by_date_goal_goal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_goals', to='goals.goal'),
        ),
    ]
