# Generated by Django 6.0.4 on 2026-04-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_current_value_goal_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='parent_goal',
        ),
    ]
